Repository duart38/serverless-sockets, pull requests merged in 2022-09, with the labels that each got.

#11 Dynamic init file
  src/INIT.ts
  src/config.js
  src/mod.ts
Labels: should have

#12 Re-exporting interfaces
  src/mod.ts
Labels: should have

#15 Enforce plug return type
  src/interface/message.ts
  src/interface/socketFunction.ts
  src/plugs/multiyield.ts
  src/server/Socket.ts
  tests/encdec.test.ts
Labels: should have

#19 Made INIT accept async init function
  src/mod.ts
Labels: must have

#21 Update MoSCoW Prioritization action
  .github/workflows/moscow.yml
Labels: should have

#23 Fixed preloader attempting to fetch from the repo
  src/server/PreLoader.ts
Labels: bug, must have

#24 Fix stuck when no INIT file is present
  src/components/Log.ts
  src/mod.ts
Labels: bug, must have
